/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("com.gradleup.shadow") version "9.0.0-beta4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// api -> exported
// implementation -> internal
dependencies {
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
    api("com.fasterxml.jackson.core:jackson-core:2.18.2")


    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    api("com.fasterxml.jackson.core:jackson-databind:2.18.2")


    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations
    api("com.fasterxml.jackson.core:jackson-annotations:2.18.2")

    api("com.dorkbox:Annotations:3.1")

	compileOnly("org.projectlombok:lombok:1.18.36")
	annotationProcessor("org.projectlombok:lombok:1.18.36")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.shadowJar {
   relocate("com.fasterxml.jackson", "io.github.goldeneas.jackson")
   relocate("com.dorkbox", "io.github.goldeneas.dorkbox")
}
